---
# tasks file for ansible-role-aws-cloudwatch-service
- name: Download file CWA
  get_url:
    url: https://s3.amazonaws.com/amazoncloudwatch-agent/debian/amd64/latest/amazon-cloudwatch-agent.deb
    dest: /opt/amazon-cloudwatch-agent.deb
    checksum: md5:e82c7444b712e237a7213d6b117d2892

- name: Install CWA .deb package
  apt:
    deb: /opt/amazon-cloudwatch-agent.deb

- name: fetching CWA configuration
  shell: /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -a fetch-config -m ec2 -s

- name: copying json custom metrics
  template:
    src: custom-metrics-advanced-cwa.json
    dest: /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.d/default
    mode: 0755
    owner: root
    group: root
  notify: amazon-cloudwatch-agent-restart

...